services:
  app:
    image: gcr.io/real-estate-labeler/image-labeler-flask
    container_name: image-labeler-flask
    build:
      context: .
      dockerfile: Dockerfile # Ensure this matches your Dockerfile name
    environment:
      FLASK_SECRET_KEY: "${FLASK_SECRET_KEY}"
      APP_ENV: "${APP_ENV:-local}"
      GOOGLE_APPLICATION_CREDENTIALS: "/var/secrets/gcp-service-account.json"
      GOOGLE_CLOUD_PROJECT_ID: "${GOOGLE_CLOUD_PROJECT_ID}"
      FIRESTORE_COLLECTION_NAME: "${FIRESTORE_COLLECTION_NAME}"
      FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}"
    volumes:
      - ./secrets/gcp-service-account.json:/var/secrets/gcp-service-account.json:ro
    ports:
      - "8080:8080"
